### ISSUE TITLE
Arduino support

### ISSUE THREAD

**Issue by DoomHammer** [bazwilliams/home-automation#1]
Hi!

Sorry for this kind of contact but I couldn't find your e-mail address anywhere. Do you think your RCU could work with something like that: http://www.instructables.com/id/RF-315433-MHz-Transmitter-receiver-Module-and-Ardu/ ?

**Comment by bazwilliams** [comment]
Should do; the LightwaveRF switch I've used is 433MHz and I've heard people talking about the Arduino as a simpler alternative to the RFXCom unit. There should be a library in github to communicate between Arduino and LightwaveRF. 

I've got a few more details about the switch on my blog if you haven't seen it: 
http://blog.bjw.me.uk/2015/01/linn-ds-homebrew-rcu-with-playlist.html

**Comment by kylegordon** [comment]
This might be a useful library for you... https://github.com/roberttidey/LightwaveRF

**Comment by DoomHammer** [comment]
Yes, I've read the blog and envied the solution. Thus I am thinking of replicating it and preparing Bill of Materials. I've already got Arduino and RPi as well as the mentioned receiver so the only thing needed seems to be LightwaveRF switch.

Thanks :)

**Comment by bazwilliams** [comment]
No worries! Good luck and don't hesitate to ask any questions. 

Can either use Github, the comment thread on my blog or I'm on the Linn Forums as http://forums.linn.co.uk/bb/member.php?action=profile&uid=22814
